/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HouseholdNewImport } from './routes/household/new'
import { Route as HouseholdJoinImport } from './routes/household/join'
import { Route as HouseholdHouseholdIdImport } from './routes/household/$householdId'
import { Route as HouseholdHouseholdIdChoresImport } from './routes/household/$householdId/chores'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HouseholdNewRoute = HouseholdNewImport.update({
  id: '/household/new',
  path: '/household/new',
  getParentRoute: () => rootRoute,
} as any)

const HouseholdJoinRoute = HouseholdJoinImport.update({
  id: '/household/join',
  path: '/household/join',
  getParentRoute: () => rootRoute,
} as any)

const HouseholdHouseholdIdRoute = HouseholdHouseholdIdImport.update({
  id: '/household/$householdId',
  path: '/household/$householdId',
  getParentRoute: () => rootRoute,
} as any)

const HouseholdHouseholdIdChoresRoute = HouseholdHouseholdIdChoresImport.update({
  id: '/household/$householdId/chores',
  path: '/household/$householdId/chores',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/household/new': {
      id: '/household/new'
      path: '/household/new'
      fullPath: '/household/new'
      preLoaderRoute: typeof HouseholdNewImport
      parentRoute: typeof rootRoute
    }
    '/household/join': {
      id: '/household/join'
      path: '/household/join'
      fullPath: '/household/join'
      preLoaderRoute: typeof HouseholdJoinImport
      parentRoute: typeof rootRoute
    }
    '/household/$householdId': {
      id: '/household/$householdId'
      path: '/household/$householdId'
      fullPath: '/household/$householdId'
      preLoaderRoute: typeof HouseholdHouseholdIdImport
      parentRoute: typeof rootRoute
    }
    '/household/$householdId/chores': {
      id: '/household/$householdId/chores'
      path: '/household/$householdId/chores'
      fullPath: '/household/$householdId/chores'
      preLoaderRoute: typeof HouseholdHouseholdIdChoresImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/household/new': typeof HouseholdNewRoute
  '/household/join': typeof HouseholdJoinRoute
  '/household/$householdId': typeof HouseholdHouseholdIdRoute
  '/household/$householdId/chores': typeof HouseholdHouseholdIdChoresRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/household/new': typeof HouseholdNewRoute
  '/household/join': typeof HouseholdJoinRoute
  '/household/$householdId': typeof HouseholdHouseholdIdRoute
  '/household/$householdId/chores': typeof HouseholdHouseholdIdChoresRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/household/new': typeof HouseholdNewRoute
  '/household/join': typeof HouseholdJoinRoute
  '/household/$householdId': typeof HouseholdHouseholdIdRoute
  '/household/$householdId/chores': typeof HouseholdHouseholdIdChoresRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/household/new' | '/household/join' | '/household/$householdId' | '/household/$householdId/chores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/household/new' | '/household/join' | '/household/$householdId' | '/household/$householdId/chores'
  id: '__root__' | '/' | '/household/new' | '/household/join' | '/household/$householdId' | '/household/$householdId/chores'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseholdNewRoute: typeof HouseholdNewRoute
  HouseholdJoinRoute: typeof HouseholdJoinRoute
  HouseholdHouseholdIdRoute: typeof HouseholdHouseholdIdRoute
  HouseholdHouseholdIdChoresRoute: typeof HouseholdHouseholdIdChoresRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseholdNewRoute: HouseholdNewRoute,
  HouseholdJoinRoute: HouseholdJoinRoute,
  HouseholdHouseholdIdRoute: HouseholdHouseholdIdRoute,
  HouseholdHouseholdIdChoresRoute: HouseholdHouseholdIdChoresRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
