export type DefaultChore = {
	key: string;
	room: string;
	name: string;
	description?: string;
	frequency: "daily" | "weekly" | "monthly" | "custom";
	frequencyDays?: number;
	defaultSpoonCost: number;
	isUnpleasant: boolean;
	icon: string;
};

export const defaultChores: DefaultChore[] = [
	{
		key: "kitchen-dishes",
		room: "Kitchen",
		name: "Wash dishes",
		description: "Clean dishes, cups, and utensils after meals.",
		frequency: "daily",
		defaultSpoonCost: 2,
		isUnpleasant: true,
		icon: "utensils",
	},
	{
		key: "kitchen-wipe-counters",
		room: "Kitchen",
		name: "Wipe counters",
		description: "Clear crumbs and wipe down kitchen surfaces.",
		frequency: "daily",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "sparkles",
	},
	{
		key: "kitchen-trash",
		room: "Kitchen",
		name: "Take out trash",
		description: "Empty kitchen trash and replace the bag.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: true,
		icon: "trash-2",
	},
	{
		key: "bathroom-clean-sink",
		room: "Bathroom",
		name: "Clean sink",
		description: "Wipe down the sink and faucet.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "sink",
	},
	{
		key: "bathroom-toilet",
		room: "Bathroom",
		name: "Clean toilet",
		description: "Scrub the bowl and wipe the exterior.",
		frequency: "weekly",
		defaultSpoonCost: 3,
		isUnpleasant: true,
		icon: "bath",
	},
	{
		key: "bathroom-mirror",
		room: "Bathroom",
		name: "Wipe mirror",
		description: "Clean bathroom mirrors and counters.",
		frequency: "weekly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "spray-can",
	},
	{
		key: "bedroom-make-bed",
		room: "Bedroom",
		name: "Make the bed",
		description: "Tidy blankets and pillows.",
		frequency: "daily",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "bed-double",
	},
	{
		key: "bedroom-laundry",
		room: "Bedroom",
		name: "Put away laundry",
		description: "Fold and put away clean clothes.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "shirt",
	},
	{
		key: "bedroom-dust",
		room: "Bedroom",
		name: "Dust surfaces",
		description: "Dust dressers, shelves, and nightstands.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "lamp",
	},
	{
		key: "living-room-tidy",
		room: "Living Room",
		name: "Tidy living room",
		description: "Pick up items and reset the space.",
		frequency: "daily",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "sofa",
	},
	{
		key: "living-room-vacuum",
		room: "Living Room",
		name: "Vacuum floors",
		description: "Vacuum rugs and high-traffic areas.",
		frequency: "weekly",
		defaultSpoonCost: 3,
		isUnpleasant: true,
		icon: "broom",
	},
	{
		key: "living-room-dust",
		room: "Living Room",
		name: "Dust surfaces",
		description: "Dust shelves, tables, and electronics.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "tv",
	},
	{
		key: "laundry-wash",
		room: "Laundry",
		name: "Wash laundry",
		description: "Run a load of laundry.",
		frequency: "weekly",
		defaultSpoonCost: 3,
		isUnpleasant: false,
		icon: "droplets",
	},
	{
		key: "laundry-fold",
		room: "Laundry",
		name: "Fold laundry",
		description: "Fold and stack clean clothes.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "shirt",
	},
	{
		key: "laundry-linens",
		room: "Laundry",
		name: "Change linens",
		description: "Refresh sheets and towels.",
		frequency: "weekly",
		defaultSpoonCost: 3,
		isUnpleasant: false,
		icon: "bed-double",
	},
	{
		key: "office-desk",
		room: "Office",
		name: "Clear desk",
		description: "Reset your desk and workspace.",
		frequency: "weekly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "briefcase",
	},
	{
		key: "office-files",
		room: "Office",
		name: "File paperwork",
		description: "Sort mail and papers.",
		frequency: "monthly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "clipboard-check",
	},
	{
		key: "office-tech",
		room: "Office",
		name: "Wipe keyboard",
		description: "Clean keyboard, mouse, and screens.",
		frequency: "monthly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "laptop",
	},
	{
		key: "outdoor-trash",
		room: "Outdoor",
		name: "Take out bins",
		description: "Move bins to curb and back.",
		frequency: "weekly",
		defaultSpoonCost: 3,
		isUnpleasant: true,
		icon: "trash-2",
	},
	{
		key: "outdoor-sweep",
		room: "Outdoor",
		name: "Sweep entry",
		description: "Sweep porch or patio.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "broom",
	},
	{
		key: "outdoor-garden",
		room: "Outdoor",
		name: "Water plants",
		description: "Water outdoor plants or garden.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "leaf",
	},
	{
		key: "entryway-shoes",
		room: "Entryway",
		name: "Tidy shoes",
		description: "Put shoes away and clear the floor.",
		frequency: "weekly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "door-open",
	},
	{
		key: "entryway-coats",
		room: "Entryway",
		name: "Hang coats",
		description: "Put coats, bags, and scarves away.",
		frequency: "weekly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "shopping-bag",
	},
	{
		key: "entryway-clean",
		room: "Entryway",
		name: "Wipe surfaces",
		description: "Clean entry table and handles.",
		frequency: "weekly",
		defaultSpoonCost: 1,
		isUnpleasant: false,
		icon: "sparkles",
	},
	{
		key: "shared-planning",
		room: "Shared Areas",
		name: "Household reset",
		description: "Quick tidy of shared spaces together.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "users",
	},
	{
		key: "shared-trash",
		room: "Shared Areas",
		name: "Empty shared bins",
		description: "Empty small bins around the home.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: true,
		icon: "trash-2",
	},
	{
		key: "shared-floor",
		room: "Shared Areas",
		name: "Sweep floors",
		description: "Sweep hard floors in common areas.",
		frequency: "weekly",
		defaultSpoonCost: 2,
		isUnpleasant: false,
		icon: "broom",
	},
];
